version: "3.4"
services:
  python: #docker run --rm -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
    container_name: python
    image: subhasishpaul/python:1.0.0
    build:
      context: .
    ports:
      - 5000:5000